" Vundle prerequisites
set nocompatible
filetype off

" Include Vundle in runtime
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle (required). Your plugins below
Plugin 'VundleVim/Vundle.vim'
Plugin 'editorconfig/editorconfig-vim'

" End of Vundle prerequisites
call vundle#end()
filetype plugin indent on

" My settings
set encoding=utf-8 fileencoding=utf-8 termencoding=utf-8
set secure
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
set autoindent
set cursorline
set ignorecase
set nobackup
set nowritebackup
set noswapfile
set number
syntax on
