" Vundle prerequisites
set nocompatible
filetype off

" Include Vundle in runtime
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" Let Vundle manage Vundle (required). Your plugins below
Plugin 'VundleVim/Vundle.vim'
Plugin 'editorconfig/editorconfig-vim'
Plugin 'valloric/youcompleteme'
Plugin 'vim-syntastic/syntastic'

" End of Vundle prerequisites
call vundle#end()
filetype plugin indent on

" My settings
set encoding=utf-8 fileencoding=utf-8 termencoding=utf-8
set secure
set textwidth=0
set tabstop=4
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
set backspace=indent,eol,start
set autoindent
set cursorline
set ignorecase
set nobackup
set nowritebackup
set noswapfile
set number
set ruler
syntax on

" Syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
