#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='subl'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

export ANDROID_NDK=/Applications/android-ndk
export ANDROID_SDK=/Volumes/UPPER/Applications/android-sdk
export CLOUDSDK_HOME=~/Downloads/google-cloud-sdk
export EAP_HOME=~/Downloads/jboss-eap-7.0.0
# Java on OSX; select desired version
export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)
export POSTGRES=/Applications/Postgres.app/Contents/Versions/9.6
# I need this for svnrdump
export XCODE_DEV=/Applications/Xcode.app/Contents/Developer

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $ANDROID_NDK
  $ANDROID_SDK/build-tools/*(/om[1])
  $ANDROID_SDK/platform-tools
  $ANDROID_SDK/tools
  $CLOUDSDK_HOME/bin
  $EAP_HOME/bin
  $JAVA_HOME/bin
  $POSTGRES/bin
  $XCODE_DEV/usr/bin
  ~/.nodenv/shims
  ~/.pyenv/shims
  ~/Secure/bin
  ~/bin
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$LOGNAME"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
